# Generated by Django 4.1.13 on 2024-10-02 15:38

from django.db import migrations, models
import django.db.models.deletion
import verification_service.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("murugo_user_id", models.CharField(max_length=100)),
                ("firstname", models.CharField(max_length=100)),
                ("secondname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("role", models.CharField(max_length=100)),
                ("personalid", models.CharField(max_length=100, unique=True)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("countryCode", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=100)),
                ("phoneNumber", models.CharField(max_length=15)),
                ("id_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=verification_service.models.upload_id_file
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "image_file",
                    models.FileField(
                        upload_to=verification_service.models.upload_image_file
                    ),
                ),
                ("extracted_data", models.TextField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to="verification_service.userprofile",
                    ),
                ),
            ],
        ),
    ]
