# Generated by Django 5.1.1 on 2024-09-17 14:14

import verification_service.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=verification_service.models.rename_uploaded_file
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("extracted_data", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
