# Generated by Django 4.1.13 on 2024-10-11 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("verification_service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="user",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
